### ISSUE TITLE
Driver 2 code dump error mission chase the gunman

### ISSUE THREAD

**Issue by carnage702** [xjsxjs197/WiiSXRX_2022#63]
To trigger  start driver 2 cd 2 version 1.1  SLUS_01318 after it starts press home button go to load the save state now resume game.
You will be in the car let yourself loose then choose try again go to the car and press triangle to enter and try to drive after the gen man a dsi exeption will pop up, this happens also if you load the save normaly without save states, so its just faster to do it this way.
save files https://www.4shared.com/s/fTG95RNc6fa
![iso](https://user-images.githubusercontent.com/12446178/201531894-75ae77be-0211-4294-a362-dd7a1bd4ee99.png)

![crash](https://user-images.githubusercontent.com/12446178/201532016-b6bdbfa4-abe0-45b8-9538-abed2fcf7a7e.png)

**Comment by saulfabregwiivc** [comment]
@xjsxjs197 possibly since he's from China (i think?) he doesn't have access to 4shared so i will attach the save files to GitHub instead ;)
[Driver2 1.1 wiistation.zip](https://github.com/xjsxjs197/WiiSXRX_2022/files/9998882/Driver2.1.1.wiistation.zip)

**Comment by saulfabregwiivc** [comment]
Tried today this game with only the savefile with latest WiiStation with Lightrec but this problem still continue.

Do you have any idea what's causing the game to crash at that point?

**Comment by xjsxjs197** [comment]
Referenced the original PcsxReload Pad code, followed the correction logic, and tested it multiple times; this issue should be fixed now.

**Comment by carnage702** [comment]
thanks a lot.

**Comment by saulfabregwiivc** [comment]
I have tested the latest changes.
Driver 2 doesn't crash anymore in this mission, but only if the controller is set to "Standard".

Driver 2 actually has support for DualShock, however trying to play this mission (Chase the Gunman) when the controller is set to "Analog" it still crashes on DSI exception, by doing this same procedure like @carnage702, but this time with Analog controller (Standard controller works fine).

@xjsxjs197, can you see what part of the code for Analog (DualShock) controller is causing this game to crash?

**Comment by xjsxjs197** [comment]
Finally fixed this error, it turns out it was caused by a null pointer.
